fixtures:
  repositories:
    "apt": "git://github.com/puppetlabs/puppetlabs-apt.git"
    "mysql": "git://github.com/puppetlabs/puppetlabs-mysql.git"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "inifile": 'git://github.com/cprice-puppet/puppetlabs-inifile'
    "create_resources": 'git://github.com/puppetlabs/puppetlabs-create_resources'
  symlinks:
    "keystone": "#{source_dir}"
